[PLATFORM-1248] Swagger URL as an ENV variable
streamr-dev/api-explorer pull request #8
Opened 2020-02-20 10:47 UTC by fonty1

Process ENV var:
`SWAGGER_PATH`

The base project defines ENV variables in a really weird way. So I'm not sure if the travis builds will be able to override them properly. Give this a test and I can try again if this fails.

2020-02-21 07:44 UTC, mikhaelsantos commented
All files but index file will be fetched via CDN (like the marketplace). The change shouldnt only be specific to CDN but also to all elements as discussed here:

https://streamr-team.slack.com/archives/DAEP235PB/p1581063165000700

2020-02-21 07:45 UTC, mikhaelsantos requested changes
All files but index file will be fetched via CDN (like the marketplace). The change shouldnt only be specific to CDN but also to all elements as discussed here:

https://streamr-team.slack.com/archives/DAEP235PB/p1581063165000700

2020-03-05 11:40 UTC, fonty1 commented
> All files but index file will be fetched via CDN (like the marketplace). The change shouldnt only be specific to CDN but also to all elements as discussed here:
> 
> https://streamr-team.slack.com/archives/DAEP235PB/p1581063165000700

I'm having problems with the webpack build. Working on it, but that's why this has been delayed FYI.

2020-03-05 16:41 UTC, fonty1 commented
@mikhaelsantos this should do the trick

2020-03-06 08:55 UTC, mikhaelsantos requested changes
In staging please use the staging cdn url.

2020-03-06 09:59 UTC, fonty1 commented
> In staging please use the staging cdn url.

Is it https://marketplace-staging.streamr.com ?

2020-03-09 07:57 UTC, mikhaelsantos approved these changes

2020-03-09 07:57 UTC, merged